export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  category: 'makanan' | 'minuman' | 'aneka-es' | 'snack' | 'dessert'
  image: string | null
}

export const menuItems: MenuItem[] = [
  {
    id: 'nasi-liwet',
    name: 'Nasi Liwet',
    description: 'Nasi liwet khas solo dengan sambal goreng krecek yang menggugah selera, sayur labu siam dan kuahnya yang kaya rasa, telur ayam utuh dan suwiran ayam sebagai lauk pendampingnya, bersama cabe, kerupuk udang, dan taburan bawang goreng yang membuat nikmatnya semakin paripurna.',
    price: 16000,
    category: 'makanan',
    image: '/images/Nasi Liwet.jpg',
  },
  {
    id: 'lontong-opor',
    name: 'Lontong Opor',
    description: 'Kuah opor santan yang gurih dan harum rempah membalut lontong lembut, ditemani telur ayam utuh, suwiran ayam, dan sambal goreng krecek yang pedas menggugah — taburan bawang goreng serta kerupuk udang menutupnya dengan renyah.',
    price: 16000,
    category: 'makanan',
    image: '/images/Lontong Opor.jpg',
  },
  {
    id: 'lontong-sayur',
    name: 'Lontong Sayur',
    description: 'Lontong berselimut sayur labu siam dengan kuah santannya yang kaya rasa, telur ayam utuh di tengah, sambal goreng krecek yang menggugah selera, dan kerupuk udang di sisi.',
    price: 16000,
    category: 'makanan',
    image: '/images/Lontong Sayur.jpg',
  },
  {
    id: 'nasi-uduk',
    name: 'Nasi Uduk',
    description: 'Harum nasi santan yang menggoda, berpadu kering kentang dan kering tempe yang gurih, abon lembut, telur dadar iris, dan sambel — kerupuk udang melengkapinya.',
    price: 16000,
    category: 'makanan',
    image: '/images/Nasi Uduk.jpg',
  },
  {
    id: 'nasi-langgi',
    name: 'Nasi Langgi',
    description: 'Nasi putih dengan serundeng kelapa yang gurih, kering kentang dan kering tempe renyah, telur dadar iris, sambel, serta kerupuk udang — pilihan yang pas untuk mengawali hari.',
    price: 16000,
    category: 'makanan',
    image: '/images/Nasi Langgi.jpg',
  },
  {
    id: 'garang-asem',
    name: 'Garang Asem',
    description: 'Kuah santan gurih beradu dengan asam segar belimbing wuluh dan tomat, sayap ayam yang empuk, plus cabe yang memberi sensasi pedas membangunkan selera — kerupuk udang siap menemani.',
    price: 20000,
    category: 'makanan',
    image: '/images/Garang Asem.jpg',
  },
  {
    id: 'gudeg',
    name: 'Nasi Gudeg',
    description: 'Manis gurihnya gudeg khas Jogja di atas nasi putih hangat, bersama suwiran ayam, tahu, telur utuh, dan sambal goreng krecek — kerupuk udang melengkapi di samping.',
    price: 20000,
    category: 'makanan',
    image: '/images/Nasi Gudeg.jpg',
  },
  {
    id: 'bubur-ayam',
    name: 'Bubur Ayam',
    description: 'Bubur ayam gurih dengan topping lengkap: suwiran ayam, kering kentang, kacang kedelai, bawang goreng, dan seledri.',
    price: 12000,
    category: 'makanan',
    image: '/images/Bubur Ayam.jpeg',
  },
  {
    id: 'selat-solo',
    name: 'Selat Solo',
    description: 'Steak ala Solo: daging sapi empuk dengan kuah kental manis asam, ditemani sayuran rebus dan kentang goreng.',
    price: 20000,
    category: 'makanan',
    image: '/images/Selat Solo.jpg',
  },
  {
    id: 'nasi-ayam',
    name: 'Nasi Ayam',
    description: 'Nasi putih hangat dengan ayam goreng/ungkep bumbu tradisional, sambal, lalapan, dan kerupuk.',
    price: 20000,
    category: 'makanan',
    image: '/images/Nasi Ayam.jpeg',
  },
  {
    id: 'ayam-gecek',
    name: 'Ayam Gecek',
    description: 'Ayam paha/dada digecek di atas cobek sampai bumbu meresap, disajikan dengan nasi putih, lalapan segar, dan kerupuk udang — pedasnya bikin nagih.',
    price: 20000,
    category: 'makanan',
    image: '/images/Ayam Gecek.jpg',
  },
  {
    id: 'nasi-goreng-rumahan',
    name: 'Nasi Goreng Rumahan',
    description: 'Nasi goreng rumahan dengan bumbu sederhana, telur, suwiran ayam, dan kerupuk. Cita rasa masakan ibu.',
    price: 15000,
    category: 'makanan',
    image: '/images/Nasi Goreng Rumahan.jpeg',
  },
  {
    id: 'es-teh',
    name: 'Es Teh',
    description: 'Tersedia juga dalam versi panas.',
    price: 3000,
    category: 'minuman',
    image: '/images/Es Teh.png',
  },
  {
    id: 'es-jeruk',
    name: 'Es Jeruk',
    description: 'Tersedia juga dalam versi panas.',
    price: 4000,
    category: 'minuman',
    image: '/images/Es Jeruk.png',
  },
  {
    id: 'es-lemon-tea',
    name: 'Es Lemon Tea',
    description: 'Tersedia juga dalam versi panas.',
    price: 5000,
    category: 'minuman',
    image: '/images/Es Lemon Tea.png',
  },
  {
    id: 'susu-putih',
    name: 'Susu Putih',
    description: 'Tersedia dalam versi es maupun panas.',
    price: 5000,
    category: 'minuman',
    image: '/images/Susu Putih.png',
  },
  {
    id: 'susu-coklat',
    name: 'Susu Coklat',
    description: 'Tersedia dalam versi es maupun panas.',
    price: 5000,
    category: 'minuman',
    image: '/images/Susu Coklat.png',
  },
  {
    id: 'kopi-hitam',
    name: 'Kopi Hitam',
    description: 'Hanya disajikan panas.',
    price: 6000,
    category: 'minuman',
    image: '/images/Kopi Hitam.png',
  },
  {
    id: 'lychee-tea',
    name: 'Lychee Tea',
    description: 'Hanya disajikan dingin/es.',
    price: 8000,
    category: 'minuman',
    image: '/images/Lychee Tea.png',
  },
  {
    id: 'es-buah',
    name: 'Es Buah',
    description: 'Campuran buah segar dengan sirup dan es serut.',
    price: 10000,
    category: 'aneka-es',
    image: '/images/Es Buah.jpeg',
  },
  {
    id: 'es-campur',
    name: 'Es Campur',
    description: 'Aneka isian lengkap dengan sirup manis dan es serut.',
    price: 12000,
    category: 'aneka-es',
    image: '/images/Es Campur.jpeg',
  },
  {
    id: 'es-dawet',
    name: 'Es Dawet',
    description: 'Cendol kenyal dengan santan dan gula merah. Tersedia porsi besar (upsize) 8.000.',
    price: 5000,
    category: 'aneka-es',
    image: '/images/Es Dawet.jpeg',
  },
  {
    id: 'es-degan',
    name: 'Es Degan',
    description: 'Segar dengan daging kelapa muda dan sirup gula merah.',
    price: 8000,
    category: 'aneka-es',
    image: '/images/Es Degan.jpeg',
  },
  {
    id: 'es-kolang-kaling',
    name: 'Es Kolang-Kaling',
    description: 'Kenyal, manis, dan menyegarkan dengan sirup gula.',
    price: 6000,
    category: 'aneka-es',
    image: '/images/Es Kolang-Kaling.jpeg',
  },
  {
    id: 'jasuke',
    name: 'Jasuke',
    description: 'Jagung manis, susu, keju, dan mentega yang creamy.',
    price: 10000,
    category: 'snack',
    image: '/images/Jasuke.jpg',
  },
  {
    id: 'risol-mayo',
    name: 'Risol Mayo',
    description: 'Risol goreng renyah dengan isian mayones gurih. Satu porsi isi 4.',
    price: 12000,
    category: 'snack',
    image: '/images/Risol Mayo.jpg',
  },
  {
    id: 'bolen-pisang-coklat',
    name: 'Bolen Pisang Coklat',
    description: 'Bolu berlapis renyah isi pisang dan cokelat meleleh. Satu porsi isi 3.',
    price: 10000,
    category: 'snack',
    image: '/images/Bolen Pisang.jpg',
  },
]

export const categories = [
  { id: 'semua', label: 'Semua' },
  { id: 'makanan', label: 'Makanan' },
  { id: 'minuman', label: 'Minuman' },
  { id: 'aneka-es', label: 'Aneka Es' },
  { id: 'snack', label: 'Snack' },
  { id: 'dessert', label: 'Dessert' },
] as const
