export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  category: 'makanan' | 'minuman' | 'aneka-es' | 'snack' | 'dessert'
  image: string | null
}

export const menuItems: MenuItem[] = [
  {
    id: 'nasi-liwet',
    name: 'Nasi Liwet',
    description: 'Nasi gurih khas Solo dengan santan, daun salam, dan sereh. Disajikan hangat dengan lauk pilihan.',
    price: 16000,
    category: 'makanan',
    image: '/images/Nasi Liwet.jpg',
  },
  {
    id: 'lontong-opor',
    name: 'Lontong Opor',
    description: 'Lontong lembut dengan kuah opor ayam santan kental, dilengkapi sambal goreng kentang dan kerupuk.',
    price: 16000,
    category: 'makanan',
    image: '/images/Lontong Opor.jpg',
  },
  {
    id: 'lontong-sayur',
    name: 'Lontong Sayur',
    description: 'Lontong dengan sayur labu siam dan kuah santan kuning, telur rebus, dan sambal kemiri.',
    price: 16000,
    category: 'makanan',
    image: '/images/Lontong Sayur.jpg',
  },
  {
    id: 'nasi-uduk',
    name: 'Nasi Uduk',
    description: 'Nasi uduk Betawi harum dengan lauk: bihun goreng, orek tempe, kering kentang, dan sambal.',
    price: 16000,
    category: 'makanan',
    image: '/images/Nasi Uduk.jpg',
  },
  {
    id: 'nasi-langgi',
    name: 'Nasi Langgi',
    description: 'Nasi langgi khas Solo dengan aneka lauk: sayur gudeg, suwiran ayam, krecek, telur pindang, dan sambal goreng kentang.',
    price: 16000,
    category: 'makanan',
    image: '/images/Nasi Langgi.jpg',
  },
  {
    id: 'garang-asem',
    name: 'Garang Asem',
    description: 'Ayam kampung dibungkus daun pisang dengan kuah asam pedas segar, lengkap dengan cabai dan tomat.',
    price: 20000,
    category: 'makanan',
    image: '/images/Garang Asem.jpg',
  },
  {
    id: 'gudeg',
    name: 'Nasi Gudeg',
    description: 'Gudeg nangka muda manis khas Jogja, disajikan dengan kuah santan, ayam suwir, telur pindang, dan krecek.',
    price: 20000,
    category: 'makanan',
    image: '/images/Nasi Gudeg.jpg',
  },
  {
    id: 'bubur-ayam',
    name: 'Bubur Ayam',
    description: 'Bubur ayam gurih dengan topping lengkap: suwiran ayam, cakwe, kacang kedelai, bawang goreng, dan seledri.',
    price: 12000,
    category: 'makanan',
    image: '/images/Bubur Ayam.jpeg',
  },
  {
    id: 'selat-solo',
    name: 'Selat Solo',
    description: 'Steak ala Solo: daging sapi empuk dengan kuah kental manis asam, ditemani sayuran rebus dan kentang goreng.',
    price: 20000,
    category: 'makanan',
    image: '/images/Selat Solo.jpg',
  },
  {
    id: 'nasi-ayam',
    name: 'Nasi Ayam',
    description: 'Nasi putih hangat dengan ayam goreng/ungkep bumbu tradisional, sambal, lalapan, dan kerupuk.',
    price: 20000,
    category: 'makanan',
    image: '/images/Nasi Ayam.jpeg',
  },
  {
    id: 'ayam-gecek',
    name: 'Ayam Gecek',
    description: 'Ayam suwir pedas khas Lombok dengan plecing kangkung, nasi hangat, dan sambal tomat segar.',
    price: 20000,
    category: 'makanan',
    image: '/images/Ayam Gecek.jpg',
  },
  {
    id: 'nasi-goreng-rumahan',
    name: 'Nasi Goreng Rumahan',
    description: 'Nasi goreng rumahan dengan bumbu sederhana, telur, sosis, dan kerupuk. Cita rasa masakan ibu.',
    price: 15000,
    category: 'makanan',
    image: '/images/Nasi Goreng Rumahan.jpeg',
  },
  {
    id: 'es-teh',
    name: 'Es Teh',
    description: 'Tersedia juga dalam versi panas.',
    price: 3000,
    category: 'minuman',
    image: '/images/Es Teh.png',
  },
  {
    id: 'es-jeruk',
    name: 'Es Jeruk',
    description: 'Tersedia juga dalam versi panas.',
    price: 4000,
    category: 'minuman',
    image: '/images/Es Jeruk.png',
  },
  {
    id: 'es-lemon-tea',
    name: 'Es Lemon Tea',
    description: 'Tersedia juga dalam versi panas.',
    price: 5000,
    category: 'minuman',
    image: '/images/Es Lemon Tea.png',
  },
  {
    id: 'susu-putih',
    name: 'Susu Putih',
    description: 'Tersedia dalam versi es maupun panas.',
    price: 5000,
    category: 'minuman',
    image: '/images/Susu Putih.png',
  },
  {
    id: 'susu-coklat',
    name: 'Susu Coklat',
    description: 'Tersedia dalam versi es maupun panas.',
    price: 5000,
    category: 'minuman',
    image: '/images/Susu Coklat.png',
  },
  {
    id: 'kopi-hitam',
    name: 'Kopi Hitam',
    description: 'Hanya disajikan panas.',
    price: 6000,
    category: 'minuman',
    image: '/images/Kopi Hitam.png',
  },
  {
    id: 'lychee-tea',
    name: 'Lychee Tea',
    description: 'Hanya disajikan dingin/es.',
    price: 8000,
    category: 'minuman',
    image: '/images/Lychee Tea.png',
  },
  {
    id: 'es-buah',
    name: 'Es Buah',
    description: 'Campuran buah segar dengan sirup dan es serut.',
    price: 10000,
    category: 'aneka-es',
    image: '/images/Es Buah.jpeg',
  },
  {
    id: 'es-campur',
    name: 'Es Campur',
    description: 'Aneka isian lengkap dengan sirup manis dan es serut.',
    price: 12000,
    category: 'aneka-es',
    image: '/images/Es Campur.jpeg',
  },
  {
    id: 'es-dawet',
    name: 'Es Dawet',
    description: 'Cendol kenyal dengan santan dan gula merah. Tersedia porsi besar (upsize) 8.000.',
    price: 5000,
    category: 'aneka-es',
    image: '/images/Es Dawet.jpeg',
  },
  {
    id: 'es-degan',
    name: 'Es Degan',
    description: 'Segar dengan daging kelapa muda dan sirup gula merah.',
    price: 8000,
    category: 'aneka-es',
    image: '/images/Es Degan.jpeg',
  },
  {
    id: 'es-kolang-kaling',
    name: 'Es Kolang-Kaling',
    description: 'Kenyal, manis, dan menyegarkan dengan sirup gula.',
    price: 6000,
    category: 'aneka-es',
    image: '/images/Es Kolang-Kaling.jpeg',
  },
  {
    id: 'jasuke',
    name: 'Jasuke',
    description: 'Jagung manis, susu, keju, dan mentega yang creamy.',
    price: 10000,
    category: 'snack',
    image: '/images/Jasuke.jpg',
  },
  {
    id: 'risol-mayo',
    name: 'Risol Mayo',
    description: 'Risol goreng renyah dengan isian mayones gurih. Satu porsi isi 4.',
    price: 12000,
    category: 'snack',
    image: '/images/Risol Mayo.jpg',
  },
  {
    id: 'bolen-pisang-coklat',
    name: 'Bolen Pisang Coklat',
    description: 'Bolu berlapis renyah isi pisang dan cokelat meleleh. Satu porsi isi 3.',
    price: 10000,
    category: 'snack',
    image: '/images/Bolen Pisang.jpg',
  },
]

export const categories = [
  { id: 'semua', label: 'Semua' },
  { id: 'makanan', label: 'Makanan' },
  { id: 'minuman', label: 'Minuman' },
  { id: 'aneka-es', label: 'Aneka Es' },
  { id: 'snack', label: 'Snack' },
  { id: 'dessert', label: 'Dessert' },
] as const
